apollo:
  appId: "test"
  ip: "localhost:8888"
  cluster: "default"
  namespaceName: "application"
  key: "config"
  isBackupConfig: false
  backupConfigPath: ""
  secret: ""
  syncServerTimeout: 0
  mustStart: false
  watch: false
